repos:
  - repo: https://github.com/mrsimonemms/pre-commit-hooks
    rev: v1.2.1
    hooks:
      - id: license-eye
      - id: go-fmt-import
      - id: go-vet
        entry: go vet ./...
      - id: gofumpt
      - id: go-err-check
      - id: go-static-check
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: pretty-format-json
        args:
          - --autofix
          - --no-sort-keys
      - id: check-json
      - id: check-yaml
        exclude: ^hack
        args:
          - --allow-multiple-documents
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
      - id: conventional-pre-commit
        stages:
          - commit-msg
  - repo: https://github.com/trussworks/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: markdown-toc
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.17.2
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.64.5
    hooks:
      - id: golangci-lint
  - repo: https://github.com/mrsimonemms/toodaloo
    rev: v0.2.4
    hooks:
      - id: scan
